on:
  pull_request:

name: Publish Docker image
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: smithlabs/gomeditateapp
          context: .
          file: ./Dockerfile
          tags: ${{ steps.docker_meta.outputs.tags }}
